name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
      name: 'Build and Push'
      runs-on: ${{ matrix.os }}

      strategy:
          matrix:
            node-version: [18, 20, 22]
            os: [ubuntu-latest, windows-latest, macos-latest]
      
      # Down the code from the repository
      steps:
        - name: Checkout source code
          uses: actions/checkout@v4

      # Set NodeJS Version
        - name: Set up NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'

      # Install dependencies
        - name: Install dependencies
          run: yarn 

      # Run testes 
        - name: Running Tests
          run: yarn test

        - name: Build Docker Image
          run: docker build -t aula-ci-cd:latest .